version: "2"

services:
    sentry:
        image: sentry:${SENTRY_VERSION}
        environment:
            - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
            - SENTRY_REDIS_HOST=redis
            - SENTRY_POSTGRES_HOST=postgres
            - SENTRY_DB_USER=sentry
            - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
            - SENTRY_DB_NAME=sentry
        ports:
            - 8080:9000
        links:
            - redis
            - postgres
    
    sentry-cron:
        image: sentry:${SENTRY_VERSION}
        environment:
            - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
            - SENTRY_REDIS_HOST=redis
            - SENTRY_POSTGRES_HOST=postgres
            - SENTRY_DB_USER=sentry
            - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
            - SENTRY_DB_NAME=sentry
        command: sentry run cron
        links:
            - redis
            - postgres
    
    sentry-worker:
        image: sentry:${SENTRY_VERSION}
        environment:
            - SENTRY_SECRET_KEY=${SENTRY_SECRET_KEY}
            - SENTRY_REDIS_HOST=redis
            - SENTRY_POSTGRES_HOST=postgres
            - SENTRY_DB_USER=sentry
            - SENTRY_DB_PASSWORD=${POSTGRES_PASSWORD}
            - SENTRY_DB_NAME=sentry
        command: sentry run worker
        links:
            - redis
            - postgres

    postgres:
        image: postgres:${POSTGRES_VERSION}
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=sentry
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    redis:
        image: redis:${REDIS_VERSION}
        volumes:
            - redis-data:/data
    
volumes:
    redis-data: